### ISSUE TITLE
Publish latest to npm

### ISSUE THREAD

**Issue by HenrikJoreteg** [dei79/node-azure-ad-jwt#4]
Hey, thanks for this module! I noticed you added a cache layer in `0.1.1` but it looks like the latest version didn't get published to npm: https://www.npmjs.com/package/azure-ad-jwt

The newest one there is `0.1.0`.

Mind running an `npm publish` real quick?

**Comment by michaelkruglos** [comment]
Is this project active?

**Comment by dei79** [comment]
I published it as 0.2.0 to reduce the risk of hidden issue when people upgrading automatically.

**Comment by michaelkruglos** [comment]
Thanks
