### ISSUE TITLE
AAD 2.0 Support

### ISSUE THREAD

**Issue by grinnellian** [dei79/node-azure-ad-jwt#5]
Microsoft has added AAD 2.0 support, causing this lib to break when using on an internal Microsoft project. @bengreenier has a fix here: https://github.com/bengreenier/node-azure-ad-jwt/commit/13dafdd87467a3f6e41aea6e81daf70e8dfffaa2

**Comment by brianfoody** [comment]
Can you merge this in @dei79 ?

**Comment by dei79** [comment]
I will check the fix with some other projects to stay compatible and then it's possible to merge.

**Comment by bengreenier** [comment]
@dei79 hey - i coded up support for this a while back, but let me know if there's any issues, i'm happy to help update and resolve 😄 👍

**Comment by dei79** [comment]
I merged it and published a new major version, sorry for delay
